// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: parking/v1/parking.proto

package parkingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ParkingService_CreateParkingLot_FullMethodName  = "/parking.v1.ParkingService/CreateParkingLot"
	ParkingService_GetParkingLot_FullMethodName     = "/parking.v1.ParkingService/GetParkingLot"
	ParkingService_UpdateParkingLot_FullMethodName  = "/parking.v1.ParkingService/UpdateParkingLot"
	ParkingService_DeleteParkingLot_FullMethodName  = "/parking.v1.ParkingService/DeleteParkingLot"
	ParkingService_ListParkingLots_FullMethodName   = "/parking.v1.ParkingService/ListParkingLots"
	ParkingService_CreateParkingSpot_FullMethodName = "/parking.v1.ParkingService/CreateParkingSpot"
	ParkingService_GetParkingSpot_FullMethodName    = "/parking.v1.ParkingService/GetParkingSpot"
	ParkingService_UpdateParkingSpot_FullMethodName = "/parking.v1.ParkingService/UpdateParkingSpot"
	ParkingService_DeleteParkingSpot_FullMethodName = "/parking.v1.ParkingService/DeleteParkingSpot"
	ParkingService_ListParkingSpots_FullMethodName  = "/parking.v1.ParkingService/ListParkingSpots"
	ParkingService_ReserveSpot_FullMethodName       = "/parking.v1.ParkingService/ReserveSpot"
	ParkingService_ReleaseSpot_FullMethodName       = "/parking.v1.ParkingService/ReleaseSpot"
)

// ParkingServiceClient is the client API for ParkingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ParkingServiceClient interface {
	CreateParkingLot(ctx context.Context, in *CreateParkingLotRequest, opts ...grpc.CallOption) (*CreateParkingLotResponse, error)
	GetParkingLot(ctx context.Context, in *GetParkingLotRequest, opts ...grpc.CallOption) (*GetParkingLotResponse, error)
	UpdateParkingLot(ctx context.Context, in *UpdateParkingLotRequest, opts ...grpc.CallOption) (*UpdateParkingLotResponse, error)
	DeleteParkingLot(ctx context.Context, in *DeleteParkingLotRequest, opts ...grpc.CallOption) (*DeleteParkingLotResponse, error)
	ListParkingLots(ctx context.Context, in *ListParkingLotsRequest, opts ...grpc.CallOption) (*ListParkingLotsResponse, error)
	CreateParkingSpot(ctx context.Context, in *CreateParkingSpotRequest, opts ...grpc.CallOption) (*CreateParkingSpotResponse, error)
	GetParkingSpot(ctx context.Context, in *GetParkingSpotRequest, opts ...grpc.CallOption) (*GetParkingSpotResponse, error)
	UpdateParkingSpot(ctx context.Context, in *UpdateParkingSpotRequest, opts ...grpc.CallOption) (*UpdateParkingSpotResponse, error)
	DeleteParkingSpot(ctx context.Context, in *DeleteParkingSpotRequest, opts ...grpc.CallOption) (*DeleteParkingSpotResponse, error)
	ListParkingSpots(ctx context.Context, in *ListParkingSpotsRequest, opts ...grpc.CallOption) (*ListParkingSpotsResponse, error)
	ReserveSpot(ctx context.Context, in *ReserveSpotRequest, opts ...grpc.CallOption) (*ReserveSpotResponse, error)
	ReleaseSpot(ctx context.Context, in *ReleaseSpotRequest, opts ...grpc.CallOption) (*ReleaseSpotResponse, error)
}

type parkingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewParkingServiceClient(cc grpc.ClientConnInterface) ParkingServiceClient {
	return &parkingServiceClient{cc}
}

func (c *parkingServiceClient) CreateParkingLot(ctx context.Context, in *CreateParkingLotRequest, opts ...grpc.CallOption) (*CreateParkingLotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateParkingLotResponse)
	err := c.cc.Invoke(ctx, ParkingService_CreateParkingLot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parkingServiceClient) GetParkingLot(ctx context.Context, in *GetParkingLotRequest, opts ...grpc.CallOption) (*GetParkingLotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetParkingLotResponse)
	err := c.cc.Invoke(ctx, ParkingService_GetParkingLot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parkingServiceClient) UpdateParkingLot(ctx context.Context, in *UpdateParkingLotRequest, opts ...grpc.CallOption) (*UpdateParkingLotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateParkingLotResponse)
	err := c.cc.Invoke(ctx, ParkingService_UpdateParkingLot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parkingServiceClient) DeleteParkingLot(ctx context.Context, in *DeleteParkingLotRequest, opts ...grpc.CallOption) (*DeleteParkingLotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteParkingLotResponse)
	err := c.cc.Invoke(ctx, ParkingService_DeleteParkingLot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parkingServiceClient) ListParkingLots(ctx context.Context, in *ListParkingLotsRequest, opts ...grpc.CallOption) (*ListParkingLotsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListParkingLotsResponse)
	err := c.cc.Invoke(ctx, ParkingService_ListParkingLots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parkingServiceClient) CreateParkingSpot(ctx context.Context, in *CreateParkingSpotRequest, opts ...grpc.CallOption) (*CreateParkingSpotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateParkingSpotResponse)
	err := c.cc.Invoke(ctx, ParkingService_CreateParkingSpot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parkingServiceClient) GetParkingSpot(ctx context.Context, in *GetParkingSpotRequest, opts ...grpc.CallOption) (*GetParkingSpotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetParkingSpotResponse)
	err := c.cc.Invoke(ctx, ParkingService_GetParkingSpot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parkingServiceClient) UpdateParkingSpot(ctx context.Context, in *UpdateParkingSpotRequest, opts ...grpc.CallOption) (*UpdateParkingSpotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateParkingSpotResponse)
	err := c.cc.Invoke(ctx, ParkingService_UpdateParkingSpot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parkingServiceClient) DeleteParkingSpot(ctx context.Context, in *DeleteParkingSpotRequest, opts ...grpc.CallOption) (*DeleteParkingSpotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteParkingSpotResponse)
	err := c.cc.Invoke(ctx, ParkingService_DeleteParkingSpot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parkingServiceClient) ListParkingSpots(ctx context.Context, in *ListParkingSpotsRequest, opts ...grpc.CallOption) (*ListParkingSpotsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListParkingSpotsResponse)
	err := c.cc.Invoke(ctx, ParkingService_ListParkingSpots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parkingServiceClient) ReserveSpot(ctx context.Context, in *ReserveSpotRequest, opts ...grpc.CallOption) (*ReserveSpotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReserveSpotResponse)
	err := c.cc.Invoke(ctx, ParkingService_ReserveSpot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parkingServiceClient) ReleaseSpot(ctx context.Context, in *ReleaseSpotRequest, opts ...grpc.CallOption) (*ReleaseSpotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseSpotResponse)
	err := c.cc.Invoke(ctx, ParkingService_ReleaseSpot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ParkingServiceServer is the server API for ParkingService service.
// All implementations should embed UnimplementedParkingServiceServer
// for forward compatibility.
type ParkingServiceServer interface {
	CreateParkingLot(context.Context, *CreateParkingLotRequest) (*CreateParkingLotResponse, error)
	GetParkingLot(context.Context, *GetParkingLotRequest) (*GetParkingLotResponse, error)
	UpdateParkingLot(context.Context, *UpdateParkingLotRequest) (*UpdateParkingLotResponse, error)
	DeleteParkingLot(context.Context, *DeleteParkingLotRequest) (*DeleteParkingLotResponse, error)
	ListParkingLots(context.Context, *ListParkingLotsRequest) (*ListParkingLotsResponse, error)
	CreateParkingSpot(context.Context, *CreateParkingSpotRequest) (*CreateParkingSpotResponse, error)
	GetParkingSpot(context.Context, *GetParkingSpotRequest) (*GetParkingSpotResponse, error)
	UpdateParkingSpot(context.Context, *UpdateParkingSpotRequest) (*UpdateParkingSpotResponse, error)
	DeleteParkingSpot(context.Context, *DeleteParkingSpotRequest) (*DeleteParkingSpotResponse, error)
	ListParkingSpots(context.Context, *ListParkingSpotsRequest) (*ListParkingSpotsResponse, error)
	ReserveSpot(context.Context, *ReserveSpotRequest) (*ReserveSpotResponse, error)
	ReleaseSpot(context.Context, *ReleaseSpotRequest) (*ReleaseSpotResponse, error)
}

// UnimplementedParkingServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedParkingServiceServer struct{}

func (UnimplementedParkingServiceServer) CreateParkingLot(context.Context, *CreateParkingLotRequest) (*CreateParkingLotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateParkingLot not implemented")
}
func (UnimplementedParkingServiceServer) GetParkingLot(context.Context, *GetParkingLotRequest) (*GetParkingLotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetParkingLot not implemented")
}
func (UnimplementedParkingServiceServer) UpdateParkingLot(context.Context, *UpdateParkingLotRequest) (*UpdateParkingLotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateParkingLot not implemented")
}
func (UnimplementedParkingServiceServer) DeleteParkingLot(context.Context, *DeleteParkingLotRequest) (*DeleteParkingLotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteParkingLot not implemented")
}
func (UnimplementedParkingServiceServer) ListParkingLots(context.Context, *ListParkingLotsRequest) (*ListParkingLotsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListParkingLots not implemented")
}
func (UnimplementedParkingServiceServer) CreateParkingSpot(context.Context, *CreateParkingSpotRequest) (*CreateParkingSpotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateParkingSpot not implemented")
}
func (UnimplementedParkingServiceServer) GetParkingSpot(context.Context, *GetParkingSpotRequest) (*GetParkingSpotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetParkingSpot not implemented")
}
func (UnimplementedParkingServiceServer) UpdateParkingSpot(context.Context, *UpdateParkingSpotRequest) (*UpdateParkingSpotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateParkingSpot not implemented")
}
func (UnimplementedParkingServiceServer) DeleteParkingSpot(context.Context, *DeleteParkingSpotRequest) (*DeleteParkingSpotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteParkingSpot not implemented")
}
func (UnimplementedParkingServiceServer) ListParkingSpots(context.Context, *ListParkingSpotsRequest) (*ListParkingSpotsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListParkingSpots not implemented")
}
func (UnimplementedParkingServiceServer) ReserveSpot(context.Context, *ReserveSpotRequest) (*ReserveSpotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReserveSpot not implemented")
}
func (UnimplementedParkingServiceServer) ReleaseSpot(context.Context, *ReleaseSpotRequest) (*ReleaseSpotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseSpot not implemented")
}
func (UnimplementedParkingServiceServer) testEmbeddedByValue() {}

// UnsafeParkingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ParkingServiceServer will
// result in compilation errors.
type UnsafeParkingServiceServer interface {
	mustEmbedUnimplementedParkingServiceServer()
}

func RegisterParkingServiceServer(s grpc.ServiceRegistrar, srv ParkingServiceServer) {
	// If the following call panics, it indicates UnimplementedParkingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ParkingService_ServiceDesc, srv)
}

func _ParkingService_CreateParkingLot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateParkingLotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkingServiceServer).CreateParkingLot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParkingService_CreateParkingLot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkingServiceServer).CreateParkingLot(ctx, req.(*CreateParkingLotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParkingService_GetParkingLot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetParkingLotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkingServiceServer).GetParkingLot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParkingService_GetParkingLot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkingServiceServer).GetParkingLot(ctx, req.(*GetParkingLotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParkingService_UpdateParkingLot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateParkingLotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkingServiceServer).UpdateParkingLot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParkingService_UpdateParkingLot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkingServiceServer).UpdateParkingLot(ctx, req.(*UpdateParkingLotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParkingService_DeleteParkingLot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteParkingLotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkingServiceServer).DeleteParkingLot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParkingService_DeleteParkingLot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkingServiceServer).DeleteParkingLot(ctx, req.(*DeleteParkingLotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParkingService_ListParkingLots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListParkingLotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkingServiceServer).ListParkingLots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParkingService_ListParkingLots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkingServiceServer).ListParkingLots(ctx, req.(*ListParkingLotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParkingService_CreateParkingSpot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateParkingSpotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkingServiceServer).CreateParkingSpot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParkingService_CreateParkingSpot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkingServiceServer).CreateParkingSpot(ctx, req.(*CreateParkingSpotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParkingService_GetParkingSpot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetParkingSpotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkingServiceServer).GetParkingSpot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParkingService_GetParkingSpot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkingServiceServer).GetParkingSpot(ctx, req.(*GetParkingSpotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParkingService_UpdateParkingSpot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateParkingSpotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkingServiceServer).UpdateParkingSpot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParkingService_UpdateParkingSpot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkingServiceServer).UpdateParkingSpot(ctx, req.(*UpdateParkingSpotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParkingService_DeleteParkingSpot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteParkingSpotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkingServiceServer).DeleteParkingSpot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParkingService_DeleteParkingSpot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkingServiceServer).DeleteParkingSpot(ctx, req.(*DeleteParkingSpotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParkingService_ListParkingSpots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListParkingSpotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkingServiceServer).ListParkingSpots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParkingService_ListParkingSpots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkingServiceServer).ListParkingSpots(ctx, req.(*ListParkingSpotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParkingService_ReserveSpot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveSpotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkingServiceServer).ReserveSpot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParkingService_ReserveSpot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkingServiceServer).ReserveSpot(ctx, req.(*ReserveSpotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParkingService_ReleaseSpot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseSpotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkingServiceServer).ReleaseSpot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParkingService_ReleaseSpot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkingServiceServer).ReleaseSpot(ctx, req.(*ReleaseSpotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ParkingService_ServiceDesc is the grpc.ServiceDesc for ParkingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ParkingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "parking.v1.ParkingService",
	HandlerType: (*ParkingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateParkingLot",
			Handler:    _ParkingService_CreateParkingLot_Handler,
		},
		{
			MethodName: "GetParkingLot",
			Handler:    _ParkingService_GetParkingLot_Handler,
		},
		{
			MethodName: "UpdateParkingLot",
			Handler:    _ParkingService_UpdateParkingLot_Handler,
		},
		{
			MethodName: "DeleteParkingLot",
			Handler:    _ParkingService_DeleteParkingLot_Handler,
		},
		{
			MethodName: "ListParkingLots",
			Handler:    _ParkingService_ListParkingLots_Handler,
		},
		{
			MethodName: "CreateParkingSpot",
			Handler:    _ParkingService_CreateParkingSpot_Handler,
		},
		{
			MethodName: "GetParkingSpot",
			Handler:    _ParkingService_GetParkingSpot_Handler,
		},
		{
			MethodName: "UpdateParkingSpot",
			Handler:    _ParkingService_UpdateParkingSpot_Handler,
		},
		{
			MethodName: "DeleteParkingSpot",
			Handler:    _ParkingService_DeleteParkingSpot_Handler,
		},
		{
			MethodName: "ListParkingSpots",
			Handler:    _ParkingService_ListParkingSpots_Handler,
		},
		{
			MethodName: "ReserveSpot",
			Handler:    _ParkingService_ReserveSpot_Handler,
		},
		{
			MethodName: "ReleaseSpot",
			Handler:    _ParkingService_ReleaseSpot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "parking/v1/parking.proto",
}
