// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: parking/v1/parking.proto

package parkingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ParkingService_CreateParking_FullMethodName     = "/parking.v1.ParkingService/CreateParking"
	ParkingService_GetParking_FullMethodName        = "/parking.v1.ParkingService/GetParking"
	ParkingService_GetAllParkings_FullMethodName    = "/parking.v1.ParkingService/GetAllParkings"
	ParkingService_DeleteParking_FullMethodName     = "/parking.v1.ParkingService/DeleteParking"
	ParkingService_CreateSpot_FullMethodName        = "/parking.v1.ParkingService/CreateSpot"
	ParkingService_GetSpot_FullMethodName           = "/parking.v1.ParkingService/GetSpot"
	ParkingService_GetSpotsByParking_FullMethodName = "/parking.v1.ParkingService/GetSpotsByParking"
	ParkingService_UpdateSpotStatus_FullMethodName  = "/parking.v1.ParkingService/UpdateSpotStatus"
	ParkingService_ReserveSpot_FullMethodName       = "/parking.v1.ParkingService/ReserveSpot"
	ParkingService_ReleaseSpot_FullMethodName       = "/parking.v1.ParkingService/ReleaseSpot"
	ParkingService_DeleteSpot_FullMethodName        = "/parking.v1.ParkingService/DeleteSpot"
	ParkingService_CreateTariff_FullMethodName      = "/parking.v1.ParkingService/CreateTariff"
	ParkingService_GetTariff_FullMethodName         = "/parking.v1.ParkingService/GetTariff"
	ParkingService_UpdateTariff_FullMethodName      = "/parking.v1.ParkingService/UpdateTariff"
	ParkingService_CalculatePrice_FullMethodName    = "/parking.v1.ParkingService/CalculatePrice"
)

// ParkingServiceClient is the client API for ParkingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ParkingServiceClient interface {
	CreateParking(ctx context.Context, in *CreateParkingRequest, opts ...grpc.CallOption) (*ParkingResponse, error)
	GetParking(ctx context.Context, in *GetParkingRequest, opts ...grpc.CallOption) (*ParkingResponse, error)
	GetAllParkings(ctx context.Context, in *GetAllParkingsRequest, opts ...grpc.CallOption) (*ParkingListResponse, error)
	DeleteParking(ctx context.Context, in *DeleteParkingRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	CreateSpot(ctx context.Context, in *CreateSpotRequest, opts ...grpc.CallOption) (*SpotResponse, error)
	GetSpot(ctx context.Context, in *GetSpotRequest, opts ...grpc.CallOption) (*SpotResponse, error)
	GetSpotsByParking(ctx context.Context, in *GetSpotsByParkingRequest, opts ...grpc.CallOption) (*SpotListResponse, error)
	UpdateSpotStatus(ctx context.Context, in *UpdateSpotStatusRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	ReserveSpot(ctx context.Context, in *SpotActionRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	ReleaseSpot(ctx context.Context, in *SpotActionRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	DeleteSpot(ctx context.Context, in *DeleteSpotRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	CreateTariff(ctx context.Context, in *CreateTariffRequest, opts ...grpc.CallOption) (*TariffResponse, error)
	GetTariff(ctx context.Context, in *GetTariffRequest, opts ...grpc.CallOption) (*TariffResponse, error)
	UpdateTariff(ctx context.Context, in *UpdateTariffRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	CalculatePrice(ctx context.Context, in *CalculatePriceRequest, opts ...grpc.CallOption) (*CalculatePriceResponse, error)
}

type parkingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewParkingServiceClient(cc grpc.ClientConnInterface) ParkingServiceClient {
	return &parkingServiceClient{cc}
}

func (c *parkingServiceClient) CreateParking(ctx context.Context, in *CreateParkingRequest, opts ...grpc.CallOption) (*ParkingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParkingResponse)
	err := c.cc.Invoke(ctx, ParkingService_CreateParking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parkingServiceClient) GetParking(ctx context.Context, in *GetParkingRequest, opts ...grpc.CallOption) (*ParkingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParkingResponse)
	err := c.cc.Invoke(ctx, ParkingService_GetParking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parkingServiceClient) GetAllParkings(ctx context.Context, in *GetAllParkingsRequest, opts ...grpc.CallOption) (*ParkingListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParkingListResponse)
	err := c.cc.Invoke(ctx, ParkingService_GetAllParkings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parkingServiceClient) DeleteParking(ctx context.Context, in *DeleteParkingRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, ParkingService_DeleteParking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parkingServiceClient) CreateSpot(ctx context.Context, in *CreateSpotRequest, opts ...grpc.CallOption) (*SpotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpotResponse)
	err := c.cc.Invoke(ctx, ParkingService_CreateSpot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parkingServiceClient) GetSpot(ctx context.Context, in *GetSpotRequest, opts ...grpc.CallOption) (*SpotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpotResponse)
	err := c.cc.Invoke(ctx, ParkingService_GetSpot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parkingServiceClient) GetSpotsByParking(ctx context.Context, in *GetSpotsByParkingRequest, opts ...grpc.CallOption) (*SpotListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpotListResponse)
	err := c.cc.Invoke(ctx, ParkingService_GetSpotsByParking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parkingServiceClient) UpdateSpotStatus(ctx context.Context, in *UpdateSpotStatusRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, ParkingService_UpdateSpotStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parkingServiceClient) ReserveSpot(ctx context.Context, in *SpotActionRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, ParkingService_ReserveSpot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parkingServiceClient) ReleaseSpot(ctx context.Context, in *SpotActionRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, ParkingService_ReleaseSpot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parkingServiceClient) DeleteSpot(ctx context.Context, in *DeleteSpotRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, ParkingService_DeleteSpot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parkingServiceClient) CreateTariff(ctx context.Context, in *CreateTariffRequest, opts ...grpc.CallOption) (*TariffResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TariffResponse)
	err := c.cc.Invoke(ctx, ParkingService_CreateTariff_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parkingServiceClient) GetTariff(ctx context.Context, in *GetTariffRequest, opts ...grpc.CallOption) (*TariffResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TariffResponse)
	err := c.cc.Invoke(ctx, ParkingService_GetTariff_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parkingServiceClient) UpdateTariff(ctx context.Context, in *UpdateTariffRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, ParkingService_UpdateTariff_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parkingServiceClient) CalculatePrice(ctx context.Context, in *CalculatePriceRequest, opts ...grpc.CallOption) (*CalculatePriceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculatePriceResponse)
	err := c.cc.Invoke(ctx, ParkingService_CalculatePrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ParkingServiceServer is the server API for ParkingService service.
// All implementations should embed UnimplementedParkingServiceServer
// for forward compatibility.
type ParkingServiceServer interface {
	CreateParking(context.Context, *CreateParkingRequest) (*ParkingResponse, error)
	GetParking(context.Context, *GetParkingRequest) (*ParkingResponse, error)
	GetAllParkings(context.Context, *GetAllParkingsRequest) (*ParkingListResponse, error)
	DeleteParking(context.Context, *DeleteParkingRequest) (*ActionResponse, error)
	CreateSpot(context.Context, *CreateSpotRequest) (*SpotResponse, error)
	GetSpot(context.Context, *GetSpotRequest) (*SpotResponse, error)
	GetSpotsByParking(context.Context, *GetSpotsByParkingRequest) (*SpotListResponse, error)
	UpdateSpotStatus(context.Context, *UpdateSpotStatusRequest) (*ActionResponse, error)
	ReserveSpot(context.Context, *SpotActionRequest) (*ActionResponse, error)
	ReleaseSpot(context.Context, *SpotActionRequest) (*ActionResponse, error)
	DeleteSpot(context.Context, *DeleteSpotRequest) (*ActionResponse, error)
	CreateTariff(context.Context, *CreateTariffRequest) (*TariffResponse, error)
	GetTariff(context.Context, *GetTariffRequest) (*TariffResponse, error)
	UpdateTariff(context.Context, *UpdateTariffRequest) (*ActionResponse, error)
	CalculatePrice(context.Context, *CalculatePriceRequest) (*CalculatePriceResponse, error)
}

// UnimplementedParkingServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedParkingServiceServer struct{}

func (UnimplementedParkingServiceServer) CreateParking(context.Context, *CreateParkingRequest) (*ParkingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateParking not implemented")
}
func (UnimplementedParkingServiceServer) GetParking(context.Context, *GetParkingRequest) (*ParkingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetParking not implemented")
}
func (UnimplementedParkingServiceServer) GetAllParkings(context.Context, *GetAllParkingsRequest) (*ParkingListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllParkings not implemented")
}
func (UnimplementedParkingServiceServer) DeleteParking(context.Context, *DeleteParkingRequest) (*ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteParking not implemented")
}
func (UnimplementedParkingServiceServer) CreateSpot(context.Context, *CreateSpotRequest) (*SpotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSpot not implemented")
}
func (UnimplementedParkingServiceServer) GetSpot(context.Context, *GetSpotRequest) (*SpotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSpot not implemented")
}
func (UnimplementedParkingServiceServer) GetSpotsByParking(context.Context, *GetSpotsByParkingRequest) (*SpotListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSpotsByParking not implemented")
}
func (UnimplementedParkingServiceServer) UpdateSpotStatus(context.Context, *UpdateSpotStatusRequest) (*ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSpotStatus not implemented")
}
func (UnimplementedParkingServiceServer) ReserveSpot(context.Context, *SpotActionRequest) (*ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReserveSpot not implemented")
}
func (UnimplementedParkingServiceServer) ReleaseSpot(context.Context, *SpotActionRequest) (*ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseSpot not implemented")
}
func (UnimplementedParkingServiceServer) DeleteSpot(context.Context, *DeleteSpotRequest) (*ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSpot not implemented")
}
func (UnimplementedParkingServiceServer) CreateTariff(context.Context, *CreateTariffRequest) (*TariffResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTariff not implemented")
}
func (UnimplementedParkingServiceServer) GetTariff(context.Context, *GetTariffRequest) (*TariffResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTariff not implemented")
}
func (UnimplementedParkingServiceServer) UpdateTariff(context.Context, *UpdateTariffRequest) (*ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTariff not implemented")
}
func (UnimplementedParkingServiceServer) CalculatePrice(context.Context, *CalculatePriceRequest) (*CalculatePriceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculatePrice not implemented")
}
func (UnimplementedParkingServiceServer) testEmbeddedByValue() {}

// UnsafeParkingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ParkingServiceServer will
// result in compilation errors.
type UnsafeParkingServiceServer interface {
	mustEmbedUnimplementedParkingServiceServer()
}

func RegisterParkingServiceServer(s grpc.ServiceRegistrar, srv ParkingServiceServer) {
	// If the following call panics, it indicates UnimplementedParkingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ParkingService_ServiceDesc, srv)
}

func _ParkingService_CreateParking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateParkingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkingServiceServer).CreateParking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParkingService_CreateParking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkingServiceServer).CreateParking(ctx, req.(*CreateParkingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParkingService_GetParking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetParkingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkingServiceServer).GetParking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParkingService_GetParking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkingServiceServer).GetParking(ctx, req.(*GetParkingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParkingService_GetAllParkings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllParkingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkingServiceServer).GetAllParkings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParkingService_GetAllParkings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkingServiceServer).GetAllParkings(ctx, req.(*GetAllParkingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParkingService_DeleteParking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteParkingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkingServiceServer).DeleteParking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParkingService_DeleteParking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkingServiceServer).DeleteParking(ctx, req.(*DeleteParkingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParkingService_CreateSpot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSpotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkingServiceServer).CreateSpot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParkingService_CreateSpot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkingServiceServer).CreateSpot(ctx, req.(*CreateSpotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParkingService_GetSpot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSpotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkingServiceServer).GetSpot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParkingService_GetSpot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkingServiceServer).GetSpot(ctx, req.(*GetSpotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParkingService_GetSpotsByParking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSpotsByParkingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkingServiceServer).GetSpotsByParking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParkingService_GetSpotsByParking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkingServiceServer).GetSpotsByParking(ctx, req.(*GetSpotsByParkingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParkingService_UpdateSpotStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSpotStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkingServiceServer).UpdateSpotStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParkingService_UpdateSpotStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkingServiceServer).UpdateSpotStatus(ctx, req.(*UpdateSpotStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParkingService_ReserveSpot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpotActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkingServiceServer).ReserveSpot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParkingService_ReserveSpot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkingServiceServer).ReserveSpot(ctx, req.(*SpotActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParkingService_ReleaseSpot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpotActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkingServiceServer).ReleaseSpot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParkingService_ReleaseSpot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkingServiceServer).ReleaseSpot(ctx, req.(*SpotActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParkingService_DeleteSpot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSpotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkingServiceServer).DeleteSpot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParkingService_DeleteSpot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkingServiceServer).DeleteSpot(ctx, req.(*DeleteSpotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParkingService_CreateTariff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTariffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkingServiceServer).CreateTariff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParkingService_CreateTariff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkingServiceServer).CreateTariff(ctx, req.(*CreateTariffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParkingService_GetTariff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTariffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkingServiceServer).GetTariff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParkingService_GetTariff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkingServiceServer).GetTariff(ctx, req.(*GetTariffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParkingService_UpdateTariff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTariffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkingServiceServer).UpdateTariff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParkingService_UpdateTariff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkingServiceServer).UpdateTariff(ctx, req.(*UpdateTariffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParkingService_CalculatePrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculatePriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkingServiceServer).CalculatePrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParkingService_CalculatePrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkingServiceServer).CalculatePrice(ctx, req.(*CalculatePriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ParkingService_ServiceDesc is the grpc.ServiceDesc for ParkingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ParkingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "parking.v1.ParkingService",
	HandlerType: (*ParkingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateParking",
			Handler:    _ParkingService_CreateParking_Handler,
		},
		{
			MethodName: "GetParking",
			Handler:    _ParkingService_GetParking_Handler,
		},
		{
			MethodName: "GetAllParkings",
			Handler:    _ParkingService_GetAllParkings_Handler,
		},
		{
			MethodName: "DeleteParking",
			Handler:    _ParkingService_DeleteParking_Handler,
		},
		{
			MethodName: "CreateSpot",
			Handler:    _ParkingService_CreateSpot_Handler,
		},
		{
			MethodName: "GetSpot",
			Handler:    _ParkingService_GetSpot_Handler,
		},
		{
			MethodName: "GetSpotsByParking",
			Handler:    _ParkingService_GetSpotsByParking_Handler,
		},
		{
			MethodName: "UpdateSpotStatus",
			Handler:    _ParkingService_UpdateSpotStatus_Handler,
		},
		{
			MethodName: "ReserveSpot",
			Handler:    _ParkingService_ReserveSpot_Handler,
		},
		{
			MethodName: "ReleaseSpot",
			Handler:    _ParkingService_ReleaseSpot_Handler,
		},
		{
			MethodName: "DeleteSpot",
			Handler:    _ParkingService_DeleteSpot_Handler,
		},
		{
			MethodName: "CreateTariff",
			Handler:    _ParkingService_CreateTariff_Handler,
		},
		{
			MethodName: "GetTariff",
			Handler:    _ParkingService_GetTariff_Handler,
		},
		{
			MethodName: "UpdateTariff",
			Handler:    _ParkingService_UpdateTariff_Handler,
		},
		{
			MethodName: "CalculatePrice",
			Handler:    _ParkingService_CalculatePrice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "parking/v1/parking.proto",
}
